[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "RL"
version = "0.1.0"
description = "Toolkit for reinforcement learning experiments"
authors = [{ name = "Cristopher Erazo", email = "cerazova@sissa.it" }]
requires-python = ">=3.10"
dynamic = ["dependencies"]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
